volumes:
  db_data:

services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'jotape'
      POSTGRES_PASSWORD: 'jotape123'
    ports:
      - 5432:5432